// Generated by listennotes/devtools/api-sdks/sync.py java. Do not edit.
package com.listennotes.podcast_api;

import java.util.Map;
import com.listennotes.podcast_api.exception.ListenApiException;

/** Endpoint methods shared by the Listen API client. */
public abstract class ApiMethods {
    protected abstract ApiResponse requestApi(String method, String path, String[] pathNames,
            String[] queryNames, Map<String, String> parameters) throws ListenApiException;

    /** Full-text search
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse search(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/search",
                new String[] {}, new String[] {"q", "sort_by_date", "type", "offset", "len_min", "len_max", "episode_count_min", "episode_count_max", "update_freq_min", "update_freq_max", "genre_ids", "published_before", "published_after", "only_in", "language", "region", "ocid", "ncid", "safe_mode", "unique_podcasts", "interviews_only", "sponsored_only", "page_size"}, parameters);
    }

    /** Typeahead search
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse typeahead(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/typeahead",
                new String[] {}, new String[] {"q", "show_podcasts", "show_genres", "safe_mode"}, parameters);
    }

    /** Find individual episodes by searching for their titles
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse searchEpisodeTitles(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/search_episode_titles",
                new String[] {}, new String[] {"q", "podcast_id", "podcast_id_type"}, parameters);
    }

    /** Spell check on a search term
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse spellcheck(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/spellcheck",
                new String[] {}, new String[] {"q"}, parameters);
    }

    /** Fetch related search terms
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchRelatedSearches(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/related_searches",
                new String[] {}, new String[] {"q"}, parameters);
    }

    /** Fetch trending search terms
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchTrendingSearches(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/trending_searches",
                new String[] {}, new String[] {}, parameters);
    }

    /** Fetch a list of best podcasts by genre
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchBestPodcasts(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/best_podcasts",
                new String[] {}, new String[] {"genre_id", "page", "region", "publisher_region", "language", "sort", "safe_mode"}, parameters);
    }

    /** Fetch detailed meta data and episodes for a podcast by id
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchPodcastById(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/podcasts/{id}",
                new String[] {"id"}, new String[] {"next_episode_pub_date", "sort"}, parameters);
    }

    /** Request to delete a podcast
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse deletePodcast(Map<String, String> parameters) throws ListenApiException {
        return requestApi("DELETE", "/podcasts/{id}",
                new String[] {"id"}, new String[] {"reason"}, parameters);
    }

    /** Fetch detailed meta data for an episode by id
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchEpisodeById(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/episodes/{id}",
                new String[] {"id"}, new String[] {"show_transcript"}, parameters);
    }

    /** Batch fetch basic meta data for episodes
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse batchFetchEpisodes(Map<String, String> parameters) throws ListenApiException {
        return requestApi("POST", "/episodes",
                new String[] {}, new String[] {}, parameters);
    }

    /** Batch fetch basic meta data for podcasts
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse batchFetchPodcasts(Map<String, String> parameters) throws ListenApiException {
        return requestApi("POST", "/podcasts",
                new String[] {}, new String[] {}, parameters);
    }

    /** Fetch a curated list of podcasts by id
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchCuratedPodcastsListById(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/curated_podcasts/{id}",
                new String[] {"id"}, new String[] {}, parameters);
    }

    /** Fetch a list of podcast genres
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchPodcastGenres(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/genres",
                new String[] {}, new String[] {"top_level_only"}, parameters);
    }

    /** Fetch a list of supported countries/regions for best podcasts
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchPodcastRegions(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/regions",
                new String[] {}, new String[] {}, parameters);
    }

    /** @see #fetchPodcastRegions(Map) */
    public ApiResponse fetchPodcastRegions() throws ListenApiException {
        return fetchPodcastRegions(Map.of());
    }

    /** Fetch a list of supported languages for podcasts
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchPodcastLanguages(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/languages",
                new String[] {}, new String[] {}, parameters);
    }

    /** @see #fetchPodcastLanguages(Map) */
    public ApiResponse fetchPodcastLanguages() throws ListenApiException {
        return fetchPodcastLanguages(Map.of());
    }

    /** Fetch a random podcast episode
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse justListen(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/just_listen",
                new String[] {}, new String[] {}, parameters);
    }

    /** @see #justListen(Map) */
    public ApiResponse justListen() throws ListenApiException {
        return justListen(Map.of());
    }

    /** Fetch curated lists of podcasts
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchCuratedPodcastsLists(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/curated_podcasts",
                new String[] {}, new String[] {"page"}, parameters);
    }

    /** Fetch recommendations for a podcast
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchRecommendationsForPodcast(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/podcasts/{id}/recommendations",
                new String[] {"id"}, new String[] {"safe_mode"}, parameters);
    }

    /** Fetch recommendations for an episode
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchRecommendationsForEpisode(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/episodes/{id}/recommendations",
                new String[] {"id"}, new String[] {"safe_mode"}, parameters);
    }

    /** Submit a podcast to Listen Notes database
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse submitPodcast(Map<String, String> parameters) throws ListenApiException {
        return requestApi("POST", "/podcasts/submit",
                new String[] {}, new String[] {}, parameters);
    }

    /** Fetch a playlist's info and items (i.e., episodes or podcasts).
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchPlaylistById(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/playlists/{id}",
                new String[] {"id"}, new String[] {"type", "last_timestamp_ms", "sort"}, parameters);
    }

    /** Fetch a list of your playlists.
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchMyPlaylists(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/playlists",
                new String[] {}, new String[] {"sort", "page"}, parameters);
    }

    /** Fetch audience demographics for a podcast
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchAudienceForPodcast(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/podcasts/{id}/audience",
                new String[] {"id"}, new String[] {}, parameters);
    }

    /** Fetch podcasts by a publisher's domain name
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse fetchPodcastsByDomain(Map<String, String> parameters) throws ListenApiException {
        return requestApi("GET", "/podcasts/domains/{domain_name}",
                new String[] {"domain_name"}, new String[] {"page"}, parameters);
    }

    /** Create a playlist.
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse createPlaylist(Map<String, String> parameters) throws ListenApiException {
        return requestApi("POST", "/playlists",
                new String[] {}, new String[] {}, parameters);
    }

    /** Update playlist metadata.
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse updatePlaylist(Map<String, String> parameters) throws ListenApiException {
        return requestApi("PUT", "/playlists/{id}",
                new String[] {"id"}, new String[] {}, parameters);
    }

    /** Delete a playlist.
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse deletePlaylist(Map<String, String> parameters) throws ListenApiException {
        return requestApi("DELETE", "/playlists/{id}",
                new String[] {"id"}, new String[] {}, parameters);
    }

    /** Add an episode or podcast to a playlist.
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse addPlaylistItem(Map<String, String> parameters) throws ListenApiException {
        return requestApi("POST", "/playlists/{id}/items",
                new String[] {"id"}, new String[] {}, parameters);
    }

    /** Remove an item from a playlist.
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse deletePlaylistItem(Map<String, String> parameters) throws ListenApiException {
        return requestApi("DELETE", "/playlists/{id}/items/{item_id}",
                new String[] {"id", "item_id"}, new String[] {}, parameters);
    }

    /** Update notes for a playlist item.
     * @param parameters path, query, and form values
     * @return API response, including response headers
     * @throws ListenApiException on invalid input, connection failure, or a non-2xx response
     */
    public ApiResponse updatePlaylistItemNotes(Map<String, String> parameters) throws ListenApiException {
        return requestApi("PUT", "/playlists/{id}/items/{item_id}",
                new String[] {"id", "item_id"}, new String[] {}, parameters);
    }

}
